before_script:
  - docker version
  - docker-compose version
  - docker-compose down --rmi all

build:
  script:
    - docker-compose build --no-cache
  stage: build
  tags:
    - auth

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - auth